/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project_a;

import java.awt.Color;
import java.awt.Component;
import java.awt.Graphics2D;
import java.awt.GraphicsConfiguration;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import java.awt.Image;
import java.awt.Transparency;
import java.awt.image.BufferedImage;
import java.io.File;
import java.util.ArrayList;
import java.util.EventObject;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JTable;
import javax.swing.UIManager;
import javax.swing.border.EmptyBorder;
import javax.swing.event.CellEditorListener;
import javax.swing.filechooser.FileSystemView;
import javax.swing.table.TableCellEditor;
import javax.swing.table.TableCellRenderer;
import org.apache.commons.io.FilenameUtils;
import org.apache.commons.lang3.StringUtils;

/**
 *
 * @author vian
 */
//This class helps us get icons to be shown in the JTable. It can be customized to show different components in a table cell
public class Icons_JTable extends javax.swing.JPanel implements TableCellRenderer, TableCellEditor{

    ArrayList<String> iconTypes;
 
    /**
     * Creates new form FileIconAndName
     */
    public Icons_JTable() {
        initComponents();
        
       
    }

   
    public Icons_JTable(ArrayList<String> iconTypes){
        this();
        
        this.iconTypes = iconTypes;
       
    }
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(20, 77));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked

    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    @Override
    public Component getTableCellRendererComponent( JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column ){

        //*** set icons
       // String iconType  = iconTypes.get(row);
        
    String iconType;
        
        if(iconTypes.size() == 0)
              iconType = "";
        else
        if(iconTypes.size() == 1)
           iconType = iconTypes.get(0);
        else
            iconType = iconTypes.get(row);
        
        ImageIcon icon = null;
        
        if(null != iconTypes){
        if(row < iconTypes.size()){
         
            switch(iconType){
                case "Computer":
                    //icon = StaticValues.monitor_x_20;
                    break;
                    
                case "Phone android":
                    
                    break;
                    
                case "hardDrive":
                  // icon = StaticValues.harddrive_x_20;
                    break;
           
                case "cdDrive":
                      icon = StaticValues.cd_x_20;
                    break;
                    
                case "folder":
  
                        icon = StaticValues.folder_blue_x_20;
                        if(StaticValues.military_theme){
                            icon = StaticValues.folder_gray_x_20;
                        }
                        //icon = new ImageIcon(iconToImage(UIManager.getIcon("FileView.directoryIcon")));
                    break;
                    
                default: 
                    File file = new File(iconType); //Note icontype is represents actual file name
                 
                    String fileExtension = FilenameUtils.getExtension(iconType);
                    
                    //if statements are suitable instead of a switch because we some extensions could contain upper and small case
                    if(StringUtils.equalsIgnoreCase(fileExtension, "txt"))
                        icon = StaticValues.file_txt_x_20;
                    else
                        if(StringUtils.equalsIgnoreCase(fileExtension, "mp3"))
                           icon = StaticValues.file_mp3_x_20;
                    else
                            if(StringUtils.equalsIgnoreCase(fileExtension, "doc") || StringUtils.equalsIgnoreCase(fileExtension, "docx"))
                             icon = StaticValues.file_doc_x_20;
                    else
                                if(StringUtils.equalsIgnoreCase(fileExtension, "indd"))
                                     icon = StaticValues.file_indd_16;
                    else
                                    if(StringUtils.equalsIgnoreCase(fileExtension, "ai"))
                                         icon = StaticValues.file_ai_x_20;
                    else
                                        if(StringUtils.equalsIgnoreCase(fileExtension, "eps"))
                                            icon = StaticValues.file_eps_x_20;
                    else
                                            if(StringUtils.equalsIgnoreCase(fileExtension, "pdf"))
                                                icon = StaticValues.file_pdf_x_20;
                    else
                                                if(StringUtils.equalsIgnoreCase(fileExtension, "svg"))
                                                    icon = StaticValues.file_svg_x_20;
                    else
                                                    if(StringUtils.equalsIgnoreCase(fileExtension, "pps") )
                                                        icon = StaticValues.file_pps_x_20;
                    else
                                                        if(StringUtils.equalsIgnoreCase(fileExtension, "ppt"))
                                                          icon = StaticValues.file_ppt_x_20;
                    else
                                                            if(StringUtils.equalsIgnoreCase(fileExtension, "rtf"))
                                                                icon = StaticValues.file_rtf_x_20;
                    else
                                                                if(StringUtils.equalsIgnoreCase(fileExtension, "xls"))
                                                                    icon = StaticValues.file_xls_x_20;
                    else
                                                                    if(StringUtils.equalsIgnoreCase(fileExtension, "bmp"))
                                                                        icon = StaticValues.file_bmp_x_20;
                    else
                                                                        if(StringUtils.equalsIgnoreCase(fileExtension, "aac"))
                                                                            icon = StaticValues.file_aac_x_20;
                    else
                                                                            if(StringUtils.equalsIgnoreCase(fileExtension, "bin"))
                                                                                 icon = StaticValues.file_bin_x_20;
                    else
                                                                                if(StringUtils.equalsIgnoreCase(fileExtension, "cue"))
                                                                                    icon = StaticValues.file_cue_x_20;
                    else
                                                                                    if(StringUtils.equalsIgnoreCase(fileExtension, "flac"))
                                                                                        icon = StaticValues.file_flac_x_20;
                    else
                                                                                        if(StringUtils.equalsIgnoreCase(fileExtension, "gif"))
                                                                                            icon = StaticValues.file_gif_x_20;
                    else
                                                                                            if(StringUtils.equalsIgnoreCase(fileExtension, "ical"))
                                                                                                icon = StaticValues.file_ical_x_20;
                    else
                                                                                                if(StringUtils.equalsIgnoreCase(fileExtension, "inx"))
                                                                                                    icon = StaticValues.file_inx_x_20;
                    else
                                                                                                    if(StringUtils.equalsIgnoreCase(fileExtension, "iso"))
                                                                                                        icon = StaticValues.file_iso_x_20;
                    else
                                                                                                        if(StringUtils.equalsIgnoreCase(fileExtension, "jpg"))
                                                                                                            icon = StaticValues.file_jpg_x_20;
                    else
                                                                                                            if(StringUtils.equalsIgnoreCase(fileExtension, "png"))
                                                                                                                icon = StaticValues.file_png_x_20;
                    else
                                                                                                                if(StringUtils.equalsIgnoreCase(fileExtension, "psd"))
                                                                                                                    icon = StaticValues.file_psd_x_20;
                    else
                                                                                                                    if(StringUtils.equalsIgnoreCase(fileExtension, "qxd"))
                                                                                                                        icon = StaticValues.file_qxd_x_20;
                    else
                                                                                                                        if(StringUtils.equalsIgnoreCase(fileExtension, "qxp"))
                                                                                                                            icon = StaticValues.file_qxp_x_20;
                    else
                                                                                                                            if(StringUtils.equalsIgnoreCase(fileExtension, "raw"))
                                                                                                                                icon = StaticValues.file_raw_x_20;
                    else
                                                                                                                                if(StringUtils.equalsIgnoreCase(fileExtension, "tif"))
                                                                                                                                    icon = StaticValues.file_tif_x_20;
                    else
                                                                                                                                    if(StringUtils.equalsIgnoreCase(fileExtension, "vcf"))
                                                                                                                                        icon = StaticValues.file_vcf_x_20;
                    else
                                                                                                                                        if(StringUtils.equalsIgnoreCase(fileExtension, "wav"))
                                                                                                                                            icon = StaticValues.file_wav_x_20;
                    else
                                                                                                                                            if(StringUtils.equalsIgnoreCase(fileExtension, "rar"))
                                                                                                                                                icon = StaticValues.box_rar_x_20;
                    else
                                                                                                                                                if(StringUtils.equalsIgnoreCase(fileExtension, "zip"))
                                                                                                                                                    icon = StaticValues.box_zip_x_20;
                    else
                                                                                                                                                    if(StringUtils.equalsIgnoreCase(fileExtension, "avi"))
                                                                                                                                                        icon = StaticValues.file_avi_x_20;
                    else
                                                                                                                                                        if(StringUtils.equalsIgnoreCase(fileExtension, "divx"))
                                                                                                                                                            icon = StaticValues.file_divx_x_20;
                    else
                                                                                                                                                            if(StringUtils.equalsIgnoreCase(fileExtension, "flv"))
                                                                                                                                                                icon = StaticValues.file_flv_x_20;
                    else
                                                                                                                                                                if(StringUtils.equalsIgnoreCase(fileExtension, "html") || StringUtils.equalsIgnoreCase(fileExtension, "htm")  )
                                                                                                                                                                     icon = StaticValues.file_html_x_20;
                    else
                                                                                                                                                                    if(StringUtils.equalsIgnoreCase(fileExtension, "mov"))
                                                                                                                                                                        icon =  StaticValues.file_mov_x_20;
                    else
                                                                                                                                                                        if(StringUtils.equalsIgnoreCase(fileExtension, "mpg"))
                                                                                                                                                                            icon = StaticValues.file_mpg_x_20;
                    else
                                                                                                                                                                            if(StringUtils.equalsIgnoreCase(fileExtension, "php"))
                                                                                                                                                                                icon = StaticValues.file_php_x_20;
                    else
                                                                                                                                                                                if(StringUtils.equalsIgnoreCase(fileExtension, "wma"))
                                                                                                                                                                                    icon = StaticValues.file_wma_x_20;
                    else
                                                                                                                                                                                    if(StringUtils.equalsIgnoreCase(fileExtension, "xml"))
                                                                                                                                                                                        icon = StaticValues.file_xml_x_20;
                    else
                                                                                                                                                                                         try{
                                                                                                                                                                                           // icon = new ImageIcon(iconToImage(javax.swing.filechooser.FileSystemView.getFileSystemView().getSystemIcon(file)));
                                                                                                                                                                                            icon = StaticValues.document_blank_x_20;
                                                                                                                                                                                             }
                                                                                                                                                                                             catch(NullPointerException ex){
                                                                                                                                                                                                 ex.printStackTrace();
                                                                                                                                                                                             }
                           
                   
            }
                
//                jLabel1.setIcon(new javax.swing.ImageIcon("content" + File.separator + "file.png")); 
                //center the content in middle of jLabel
                jLabel3.setVerticalAlignment((int) CENTER_ALIGNMENT);
                jLabel3.setHorizontalAlignment((int) CENTER_ALIGNMENT);
               
                jLabel3.setIcon(icon);
            } 
    }
     //****
     
     //**** colours
             Color alternateColor1 = StaticValues.color_6;
             Color alternateColor2 = StaticValues.color_5;
             Color foreground_color_when_selected = Color.white;
             Color background_color_when_selected = StaticValues.color_1;
             Color foreground_color_when_not_selected = StaticValues.color_dark_2;
                                 
             if(StaticValues.military_theme){
                alternateColor1 = StaticValues.gray_4;
                alternateColor2 = StaticValues.gray_5;
                foreground_color_when_selected = Color.white;
                background_color_when_selected = Color.black;
                foreground_color_when_not_selected = Color.BLACK;
                }
     
           jPanel1.setBackground(row%2==0 ? alternateColor2 : alternateColor1); //alternate rows
                        
                                
             if(isSelected){
               jPanel1.setBackground(background_color_when_selected);
                 
                jPanel1.setForeground(foreground_color_when_selected); 
                     }
                                else{
                                    jPanel1.setBackground(row%2==0 ? alternateColor2 : alternateColor1); //alternate rows
                                    jPanel1.setForeground(foreground_color_when_not_selected);
                                }
             
            
        //renders
             /*
        if(hasFocus){
            jLabel3.setBackground(new Color(252,242,206));
//         else
//           jPanel1.setBackground(new Color(214, 217, 223));
        }
 */
      //  this.setBackground(new Color(214, 217, 223));
        
       // jPanel1.setBorder(new EmptyBorder(0, 0, 10, 0));
        return this;
    }

    @Override
    public Component getTableCellEditorComponent( JTable table, Object value, boolean isSelected, int row, int column ) {
        
        
        return this;
    }

    @Override
    public Object getCellEditorValue() {
        return null;
    }

    @Override
    public boolean isCellEditable(EventObject eo) {
            return true;
        }

    @Override
    public boolean shouldSelectCell(EventObject eo) {
        return true;
    }

    @Override
    public boolean stopCellEditing() {
        return true;
    }

    @Override
    public void cancelCellEditing() {
        
    }

    @Override
    public void addCellEditorListener(CellEditorListener cl) {
    }

    @Override
    public void removeCellEditorListener(CellEditorListener cl) {

    }
    
    //converts an icon to ImageIcon
    static Image iconToImage(Icon icon) {
        Color transparent = new Color(0, true);
        
        if(icon == null){
            icon = UIManager.getIcon("FileView.fileIcon");
            
            if(icon == null)
                return null;
        }
        
          if (icon instanceof ImageIcon) {
              return ((ImageIcon)icon).getImage();
          } else {
              int w = icon.getIconWidth();
              int h = icon.getIconHeight();
              GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
              GraphicsDevice gd = ge.getDefaultScreenDevice();
              GraphicsConfiguration gc = gd.getDefaultConfiguration();
              BufferedImage image = gc.createCompatibleImage(w, h,  Transparency.TRANSLUCENT); 
              Graphics2D g = image.createGraphics();
              icon.paintIcon(null, g, 0, 0);
              g.dispose();
              return image;
          }
      }
}
